### ISSUE TITLE
Any good way to make multimethods work as component functions?

### ISSUE THREAD

**Issue by simonacca** [lilactown/helix#116]
Hi,
I realized that it doesn't seem to be possible to define components with multimethods, even with a custom macro such as
```cljs
(defmacro defmethod
     [multifn dispatch-val & form-body]
     (let [props-bindings (first form-body)
            body (rest form-body)]
       `(cljs.core/defmethod ~multifn ~dispatch-val
          [props# maybe-ref#]
          (let [~props-bindings [(helix.core/extract-cljs-props props#) maybe-ref#]]
            ~@body))))
```

Upon usage of such a component with:

```cljs
(defmulti animals (fn [props] (.-animal props)))

(my-custom-helix-macros/defmethod animals :dog
  []
  (helix/$ :div "rendering dog"))

(my-custom-helix-macros/defmethod animals :sheep
  []
  (helix/$ :div "rendering sheep"))

(helix/defnc using-multimethod
  []
  (helix/$ animals {:animal :dog})
)
```

When rendering such a component, one gets this error from React:
> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object

This seems to be because a multimethod is realized in Javascript as an object that is not callable, hence react doesn't know what to do with it.

(This is what a multimethod looks like in js: `{name: {...}, default_dispatch_val: {...}, hierarchy: {...}, method_table: {...}, ...}`.)

One could get around this without breaking the contract with React too much by defining 
`(defn animals-wrapper [& args] (apply animals args))` and calling `animal-wrappers` from `using-multimethod` instead.

Is there a more elegant way to solve this problem?
(not necessarily in helix core, also in userspace would be fine)

Thanks!

**Comment by lilactown** [comment]
React components must be either a literal JavaScript function, or an object that inherits from the `React.Component` class. Unfortunately, multi methods do not fall into those categories.

I would recommend structuring your code in a way that the _business logic_ is handled by multi method, but the component itself is a function. Similar to your examples:

```clojure
(defmulti animals :animal)

(defmethod animals :dog
  []
  "rendering dog")

(defmethod animals :sheep
  []
  "rendering sheep")

(helix/defnc using-multimethod
  []
  (helix/$ :div (animals {:animal :dog})))
```

While less powerful than using the multi method as a component itself, this protects you from a potential footgun: if your multicomponent used hooks, and the `:animal` passed in changed, it could render new hooks or need to re-initialize them based on the method used and React wouldn't know how to do that, because the identity of methods are the same no matter the branch it takes. It would be akin to:

```clojure
(defnc my-multi-component
  [{:keys [animal]}]
  (case animal
    :dog (let [[barked? set-barked] (hooks/use-state false)]
            ,,,)
    :sheep ,,,))
```

This is breaking the rule where hooks should never be _conditionally_ used inside of a component.

**Comment by lilactown** [comment]
How exactly do you implement lazy-loading this way? I'm interested to learn.

**Comment by lilactown** [comment]
Have you looked at [React.lazy](https://reactjs.org/docs/code-splitting.html#reactlazy) and [shadow.lazy], as described in [thheller's blog post](https://code.thheller.com/blog/shadow-cljs/2019/03/03/code-splitting-clojurescript.html) on code splitting?

With a bit of [macro magic](https://github.com/thheller/code-splitting-clojurescript/blob/c9e1e9340c45969f3fc5b515fb9d095f28595c24/src/main/demo/util.cljs) you can lazily load individual components really easily, and not have to resort to multi methods which adds more indirection to your application. An example of the type of API I've used in some projects:

```clojure
(def about (lazy town.lilac.app.about/page)

(defnc routes
  []
  (case (use-route)
    :home ($ home)
```

**Comment by lilactown** [comment]
I appreciate the good discussion @simonacca :)
