### ISSUE TITLE
The $ macro and new JSX transform

### ISSUE THREAD

**Issue by rome-user** [lilactown/helix#123]
According to the new React documentation released today, [React.createElement](https://react.dev/reference/react/createElement) is a legacy API, and JSX itself has used a [new transform](https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) that will allow React to perform certain optimizations in the future. The new transform is designed to be backwards compatible with existing code.

Is this something worth investigating? Possibly refactoring the $ macro to match the modern JSX output?

**Comment by lilactown** [comment]
yeah it's worth investigating. not high priority right now since `createElement` still exists, but the new jsx transform is slightly more performant which is nice.

**Comment by lilactown** [comment]
Awesome write up! Thank you for the thorough look. I look forward to reviewing the patch this weekend.

**Comment by lilactown** [comment]
Great work so far. As I was reading your bullets, I had a couple thoughts

1. Seems right to do all the object manipulation in the props macros
2. It's probably right to keep the `nil` behavior for `:key`
3. By "distinguish strings and arrays" do you mean distinguish between children as a single string or children as a seq of element types (including strings)?
4. this makes sense when emitting the right syntax, and I think your choice of emitting an array constructor is good because it's cheap
5. Can you elaborate on why that would fail because of changes to the way $ converts lists to arrays?

Very exciting, I appreciate all your work on this!

**Comment by lilactown** [comment]
💪🏻 sounds great!
